// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegisteredUsers.DataAccess.Sql.Core;

namespace RegisteredUsers.DataAccess.Sql.Migrations
{
    [DbContext(typeof(RegisteredUserContexts))]
    [Migration("20200529051131_SeedNewData")]
    partial class SeedNewData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegisteredUsers.DataAccess.Sql.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArticleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BoardInvitations")
                        .HasColumnType("int");

                    b.Property<int>("BoardInvitationsAccepted")
                        .HasColumnType("int");

                    b.Property<int>("BoardInvitationsDeclined")
                        .HasColumnType("int");

                    b.Property<int>("BoardInvitationsPending")
                        .HasColumnType("int");

                    b.Property<int>("BoardInvitationsRemoveFromBoard")
                        .HasColumnType("int");

                    b.Property<int>("BoardInvitationsRevoked")
                        .HasColumnType("int");

                    b.Property<int>("EditingAssignments")
                        .HasColumnType("int");

                    b.Property<int>("EditingAssignmentsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("EditingAssignmentsCurrent")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewAssignments")
                        .HasColumnType("int");

                    b.Property<int>("ReviewAssignmentsCurrent")
                        .HasColumnType("int");

                    b.Property<int>("ReviewAssignmentsEndosed")
                        .HasColumnType("int");

                    b.Property<int>("ReviewAssignmentsRejected")
                        .HasColumnType("int");

                    b.Property<int>("Submission")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionAccepted")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionInReview")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionInitialValidation")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionRejected")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleType = "Author",
                            Author = "TES International (United States)",
                            BoardInvitations = 1,
                            BoardInvitationsAccepted = 1,
                            BoardInvitationsDeclined = 0,
                            BoardInvitationsPending = 0,
                            BoardInvitationsRemoveFromBoard = 0,
                            BoardInvitationsRevoked = 1,
                            EditingAssignments = 0,
                            EditingAssignmentsCompleted = 1,
                            EditingAssignmentsCurrent = 1,
                            Email = "deepthir9597@gmail.com",
                            FirstName = "Deepthi",
                            LastName = "Kuzhikkattil",
                            MiddleName = "Rajesh",
                            Password = "deepthi97",
                            Place = "Troy, United States",
                            RegistrationDate = "06/11/2019",
                            ReviewAssignments = 0,
                            ReviewAssignmentsCurrent = 1,
                            ReviewAssignmentsEndosed = 1,
                            ReviewAssignmentsRejected = 0,
                            Submission = 1,
                            SubmissionAccepted = 0,
                            SubmissionInReview = 0,
                            SubmissionInitialValidation = 0,
                            SubmissionRejected = 0
                        },
                        new
                        {
                            Id = 2,
                            ArticleType = "Author",
                            Author = "TES International (United States)",
                            BoardInvitations = 1,
                            BoardInvitationsAccepted = 1,
                            BoardInvitationsDeclined = 0,
                            BoardInvitationsPending = 0,
                            BoardInvitationsRemoveFromBoard = 0,
                            BoardInvitationsRevoked = 1,
                            EditingAssignments = 0,
                            EditingAssignmentsCompleted = 1,
                            EditingAssignmentsCurrent = 0,
                            Email = "sandheepsanthosh@gmail.com",
                            FirstName = "Sandheep",
                            LastName = "Santhosh",
                            MiddleName = "",
                            Password = "sandheep95",
                            Place = "Troy, United States",
                            RegistrationDate = "28/04/2020",
                            ReviewAssignments = 0,
                            ReviewAssignmentsCurrent = 0,
                            ReviewAssignmentsEndosed = 1,
                            ReviewAssignmentsRejected = 0,
                            Submission = 1,
                            SubmissionAccepted = 0,
                            SubmissionInReview = 1,
                            SubmissionInitialValidation = 0,
                            SubmissionRejected = 1
                        },
                        new
                        {
                            Id = 3,
                            ArticleType = "Review",
                            Author = "TES International (United States)",
                            BoardInvitations = 1,
                            BoardInvitationsAccepted = 1,
                            BoardInvitationsDeclined = 0,
                            BoardInvitationsPending = 0,
                            BoardInvitationsRemoveFromBoard = 0,
                            BoardInvitationsRevoked = 1,
                            EditingAssignments = 0,
                            EditingAssignmentsCompleted = 1,
                            EditingAssignmentsCurrent = 0,
                            Email = "keerthana95@gmail.com",
                            FirstName = "Keerthana",
                            LastName = "Nair",
                            MiddleName = "L",
                            Password = "keerthana97",
                            Place = "Troy, United States",
                            RegistrationDate = "28/04/2020",
                            ReviewAssignments = 0,
                            ReviewAssignmentsCurrent = 0,
                            ReviewAssignmentsEndosed = 1,
                            ReviewAssignmentsRejected = 0,
                            Submission = 1,
                            SubmissionAccepted = 0,
                            SubmissionInReview = 1,
                            SubmissionInitialValidation = 0,
                            SubmissionRejected = 1
                        },
                        new
                        {
                            Id = 4,
                            ArticleType = "Associate Editor",
                            Author = "TES International (United States)",
                            BoardInvitations = 0,
                            BoardInvitationsAccepted = 1,
                            BoardInvitationsDeclined = 0,
                            BoardInvitationsPending = 1,
                            BoardInvitationsRemoveFromBoard = 0,
                            BoardInvitationsRevoked = 1,
                            EditingAssignments = 0,
                            EditingAssignmentsCompleted = 1,
                            EditingAssignmentsCurrent = 0,
                            Email = "malukannan95@gmail.com",
                            FirstName = "Malu",
                            LastName = "",
                            MiddleName = "Kannan",
                            Password = "malu97",
                            Place = "Troy, United States",
                            RegistrationDate = "28/04/2010",
                            ReviewAssignments = 0,
                            ReviewAssignmentsCurrent = 0,
                            ReviewAssignmentsEndosed = 1,
                            ReviewAssignmentsRejected = 0,
                            Submission = 1,
                            SubmissionAccepted = 1,
                            SubmissionInReview = 1,
                            SubmissionInitialValidation = 0,
                            SubmissionRejected = 1
                        },
                        new
                        {
                            Id = 5,
                            ArticleType = "Author",
                            Author = "TES International (United States)",
                            BoardInvitations = 0,
                            BoardInvitationsAccepted = 0,
                            BoardInvitationsDeclined = 1,
                            BoardInvitationsPending = 0,
                            BoardInvitationsRemoveFromBoard = 0,
                            BoardInvitationsRevoked = 1,
                            EditingAssignments = 0,
                            EditingAssignmentsCompleted = 1,
                            EditingAssignmentsCurrent = 0,
                            Email = "divyarajesh0397@outlook.com",
                            FirstName = "Divya",
                            LastName = "Kuzhikkattil",
                            MiddleName = "Rajesh",
                            Password = "divya97",
                            Place = "Troy, United States",
                            RegistrationDate = "18/09/2018",
                            ReviewAssignments = 0,
                            ReviewAssignmentsCurrent = 0,
                            ReviewAssignmentsEndosed = 1,
                            ReviewAssignmentsRejected = 0,
                            Submission = 1,
                            SubmissionAccepted = 0,
                            SubmissionInReview = 1,
                            SubmissionInitialValidation = 0,
                            SubmissionRejected = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
